### ISSUE TITLE
[REQUEST] Would it be possible to add a samples folder?

### ISSUE THREAD

**Issue by bzerangue** [ahwayakchih/templatedtextformatters#5]
@ahwayakchih - First of all, thank you for making this extension. This is exactly what I was looking for.

I was wondering if you would be willing to provide some sample text files showing the patterns that you used for the examples you have in your screenshot?

![Templated Text Formatter Extension Screenshot](https://raw.githubusercontent.com/ahwayakchih/templatedtextformatters/master/screenshots/flyer.png)
- Base64
- Celsius and Exponentiation
- Cleanup text
- CSV2XML
- Dictionary
- Documenter Markdown
- Images and Links
- Price list
- Reviews Markdown
- Strong paragraph
- Vimeo video 
- YouTube video

Unfortunately, I am not really strong on RegEx but think this would be a helpful tool for me to get better as well as adding some amazing functionality/flexibility to my textboxes in Symphony. 

If you are willing to do this, that would be extremely helpful. If not, I totally and completely understand. Either way, thank you for your hard work and for making such great extensions for Symphony. There are extremely useful!!!

Thank you so much!
Brian Z.

**Comment by ahwayakchih** [comment]
Hi,

I'm glad you like it! This extension (and all example formatters) were implemented for a project i was working on for Sylwester Cyba (http://nhl.pl), so i'll pass thanks to him :).

Here are regexes (i was manually extracting them from PHP files, and did not test them, so if you find any errors, let me know):

**1. base64**

It used `e` modifier, which is deprecated now (because it was a bit unsafe to allow regexes to call PHP functions), so i'm not sure if it can be used.

Pattern:

```
/^([\w\W\s]*)$/e
```

Replacement:

```
base64_encode('$1')
```

**2. Celsius and Exponentation**

Patterns (each line is a separate pattern, order is important):

```
/((?:[\s\>\(]|^)\d+)\^(\d+)/
/(?<=[\s\>\(]|^)(\d+(?:[,\.]\d+)?)[ ]?(mm?|cm|in|ft)([\s,\<\)]|[\.!\?\/]+(?:\s|$)|$)/
/(?<=[\s\>\(]|^)(\d+(?:[,\.]\d+)?)[ ]?(k?g|oz|lb)([\s,\<\)]|[\.!\?\/]+(?:\s|$)|$)/
/(?<=[\s\>\(]|^)(\d+(?:[,\.]\d+)?)[ ]?(C|F)([\s,\<\)]|[\.!\?\/]+(?:\s|$)|$)/e
```

Replacements:

```
$1<sup>$2</sup>
<var class="length $2" data-type="length" data-unit="$2">$1 $2</var>$3
<var class="mass $2" data-type="mass" data-unit="$2">$1 $2</var>$3
'<var class="temperature $2" data-type="temperature" data-unit="$2">$1 '.('$2' == 'F' ? '℉': '℃').'</var>$3'
```

Last one uses eval modifier, but you could try to split it into two, like this:

```
/(?<=[\s\>\(]|^)(\d+(?:[,\.]\d+)?)[ ]?(C)([\s,\<\)]|[\.!\?\/]+(?:\s|$)|$)/
/(?<=[\s\>\(]|^)(\d+(?:[,\.]\d+)?)[ ]?(F)([\s,\<\)]|[\.!\?\/]+(?:\s|$)|$)/
```

and:

```
<var class="temperature $2" data-type="temperature" data-unit="$2">$1 ℃</var>$3
<var class="temperature $2" data-type="temperature" data-unit="$2">$1 ℉</var>$3
```

**3. Cleanup text**

This one is mainly about keeping space after comma, removing multiple spaces, etc...

Patterns (each line is a separate pattern, order is important):

```
/[ ]{2,}/xs
/([a-zA-Z0-9]|ą|ż|ś|ź|ę|ć|ń|ł|Ą|Ż|Ś|Ź|Ę|Ć|Ń|Ł|\]|\)|\>)[ ]+([\.!?])([ \n\r]+|$)/xs
/[ ]+,([ ]|)/xs
/[ ]+([!?]+([ ]|[\r\n]|$))/xs
```

Replacements (first line contains a single space character):

```

$1$2$3
,$1
$1
```

**4. CSV2XML**

Another one using deprecated eval modifier. Here it is used for parsing floating point values. I guess that a lot more complicated regex could replace that, but i'm not sure how at this moment.

Patterns:

```
/(([:][ ]+)|[,][ ]+|[;\t][ ]*|^)(-?\\d+)(?:[,\.](\d+))?/xse
/(^|[\r\n]+)([^:]+):([^\r\n]+)/xsi
%<mode>([^<]+)(\s+\(([^<\)]+)\))</mode>%xsi
/>\s+</
```

Replacements:

```
'$2<result>'.floatval('$3.$4').'</result>'
$1<item><mode>$2</mode>$3</item>
<mode group="$3">$1</mode>
><
```

**5. Dictionary**

This one was just a part of whole thing, because it prepared HTML tags to be later translated using XSLT.

Pattern:

```
/(?:[\r\n]+|^)([^:]+):\s+([^\r\n$]+)/
```

Replacement:

```
<p id="$1">$2</p>
```

**6. Documenter Markdown**

This one was just a chain that grouped "cleanup text", "celsius and exponentation", "images and links", "markdown extra" and "partner of skapiec".

**7. Images and Links**

This handles a lot more standard (at least here) way of specifying images and links. For example, Markdown syntax for link is:

```
[This link](http://example.net/) has no title attribute.
```

which i find horrible to read, and think that something like this is A LOT more readable:

```
"This link" (http://example.net/) has no title attribute.
```

Similarly, Markdown syntax for images:

```
![Alt text](/path/to/img.jpg "Optional title")
```

is horrible in my opinion, and looks much better this way (the way it's used in books here):

```
[alt text: /path/to/img.jpg]
```

(It does not handle "optional title", but that could be done with some more complicated regex).

I removed one of the patterns, because it was site specific - links to specified categories/tags were marked with additional data attributes, etc...

Patterns:

```
/(\n|^)\[(([^\]\r\n]+):[ ]+|())(\w+:\/\/|\.\/|\/)([^\]\r\n\s]+\.(?:png|jpg|jpeg|gif|webp|jp2|tiff))\]([ ]*([A-Za-z0-9]))?/xis
/((")([^"]+)"|([^\s]+))[ \r\n]*?\(((([^:\/\)]+)[ ]*:[ ]+|)((?:\w+:\/\/|\.?\/|\#)[^ \r\n\)]+))\)/xs
```

Images pattern (first one) works only for images specified using square bracket at the beginning of text or line. You can remove that by clearing up first patrenthesis (so, from `(\n|^)` to `()`

Replacements:

```
$1![$3$4](\\5\\6)$8
$2[$3$4]($8 "$7")$2
```

**8. Price List**

Another one with eval modifier for parsing floating point values.

Pattern:

```
/(?:[,;]?[ ]+|^)(\d+)(?:[,\.](\d+))?/xse
```

Replacement:

```
'<span class="price">'.floatval('$1.$2').'</span>'
```

**9. Reviews Markdown**

Another chain formatter, which simply groups other formatters.

**10. Strong Paragraph**

Pattern:

```
/(\n|^)(\+[ ]*\+[ ]*\+[ ]*)([.\s\w\W]+)\2/
```

Replacement:

```
\\1<p class="strong">\\3</p>
```

**11. Vimeo and YouTube videos**

I'm sorry, but those are missing (they were replaced with different, more generic "embedding" formatter). I bet they wouldn't work with current APIs of those sites anyway.
IIRC, they simply turned things like `[watch video: http://youtube/123455]` into embedded videos, to make it easier for authors to embed videos using the same syntax as the one for embedding images.

Hope that helps :).
Regards

**Comment by bzerangue** [comment]
Wow!!! Thank you so much!!!!
